### ISSUE TITLE
Issues plotting data in flow demo

### ISSUE THREAD

**Issue by prjwlk** [ucb-art/BAG2_cds_ff_mpt#1]
running simulation
Running tasks, Press Ctrl-C to cancel.
simulation done, load results
all simulation done
loading simulation data for AMP_CS_tb_dc
loading simulation data for AMP_CS_tb_ac_tran
finish loading data
BAG2_cds_ff_mpt/BAG_XBase_demo/xbase_demo/core.py in split_data_by_sweep(results, var_list)
    203 
    204 def split_data_by_sweep(results, var_list):
--> 205     sweep_names = results['sweep_params'][var_list[0]][:-1]
    206     combo_list = []
    207     for name in sweep_names:

KeyError: 'vin'

**Comment by sbuchbinder** [comment]
Can you run
```
git submodule status
```
in BAG2_cds_ff_mpt?

We had to force-push to some of these repos, so the histories have diverged. 
If you haven't already, can you try creating a brand new BAG2_cds_ff_mpt workspace, and run again in there. That way we can at least be sure that we are running the same versions of everything.

**Comment by prjwlk** [comment]
I Fixed this issue.. I had to set up corners_setup.sdb file correctly
