### ISSUE TITLE
microtemplate

### ISSUE THREAD

**Issue by gdutee** [ucb-art/BAG2_cds_ff_mpt#10]
Hi Eric 
I have no access to cds_ff_mpt pdk, however, I have managed to get the BAG flow run w/o layout . 
For the laygo part,  is that possible to include a gds file for the cds_ff_mpt_microtemplate_dense library for viewing laygo cells.
btw, can the 'prboundary' be replaced by any other marking layers?
Thank you~

**Comment by jdhan** [comment]
Please download the gds file from here: [https://bit.ly/2FZzVym](https://bit.ly/2FZzVym)
The prboundary layer can be changed by modifying the following item in laygo_config.yaml
prboundary_layer: [prBoundary, boundary] #boundary layer
