### ISSUE TITLE
unable to run demo testbench because leak of files.

### ISSUE THREAD

**Issue by sequencer** [ucb-art/BAG2_cds_ff_mpt#11]
the `BAG_XBase_demo/demo_testbench` require files under `/tools` which seems in the Berkeley's server.
My server won't give a simulation result, while virtuoso complain about the issue of `/tools` not found.

**Comment by pkerichang** [comment]
Did you follow the instructions in the README?  What is the exact error?  Sounds like you did not update the corner files.

**Comment by sequencer** [comment]
I got `cds_ff_mpt_v0.4` form my AE, but I only have IC617 rather than ICADV12.3, maybe that's the problem.

**Comment by pkerichang** [comment]
Ah, I remember we encounter this issue at Berkeley; I think for some reason IC617 has this bug, but IC616 should work.
