### ISSUE TITLE
Simulations don't run on a centos 7 installation

### ISSUE THREAD

**Issue by matangk** [ucb-art/BAG2_cds_ff_mpt#12]
Hi, For all I know I have tried to run the demo on a centos6 and centos7 installations. Definitions were set identically by following the readme instructions.
1_flow_demo runs fine on Centos6, including simulation and plots.
On Centos7, all the steps before the simulation run fine, but the simulation itself hangs. It throws an error after several minutes (timeout probably).
Is the demo verified to run on Centos7/RHEL7? If so, am I missing some path definition?
Traceback:
using existing BagProject
computing layout
ext_w0 = 1, ext_wend=1, ytop=2592
final: ext_w0 = 1, ext_wend=1, ytop=2592
{'s': WireArray(TrackID(layer=3, track=7, num=9, pitch=2), 1109, 1265, 0.001), 'd': WireArray(TrackID(layer=3, track=8, num=8, pitch=2), 1231, 1387, 0.001), 'g': WireArray(TrackID(layer=3, track=8, num=8, pitch=2), 915, 1071, 0.001)}
WireArray(TrackID(layer=3, track=8, num=8, pitch=2), 915, 1071, 0.001)
6.5
creating layout
layout done
computing AMP_CS schematics
creating AMP_CS schematics
running lvs
Running tasks, Press Ctrl-C to cancel.
lvs passed
lvs log is /home/mgal/Cadence/BAG2_cds_ff_mpt/pvs_run/lvs_run_dir/DEMO_AMP_CS/AMP_CS/lvsLog_20181130_235100uue_tc3j
computing AMP_CS_tb_ac_tran schematics
creating AMP_CS_tb_ac_tran schematics
schematic done
setting up AMP_CS_tb_ac_tran
running simulation
Running tasks, Press Ctrl-C to cancel.
simulation done, load results
Traceback (most recent call last):

  File "<ipython-input-5-3095eb1d5f78>", line 22, in <module>
    demo_core.run_flow(bprj, top_specs, 'amp_cs', layout_core.AmpCS, run_lvs=True)

  File "/home/mgal/Cadence/BAG2_cds_ff_mpt/BAG_XBase_demo/xbase_demo/core.py", line 386, in run_flow
    simulate(prj, specs, dsn_name)

  File "/home/mgal/Cadence/BAG2_cds_ff_mpt/BAG_XBase_demo/xbase_demo/core.py", line 175, in simulate
    results = load_sim_results(tb.save_dir)

  File "/home/mgal/Cadence/BAG2_cds_ff_mpt/BAG_framework/bag/io/sim_data.py", line 131, in load_sim_results
    top_swp_list, values_list = _get_sweep_params(os.path.join(save_dir, 'sweep.info'))

  File "/home/mgal/Cadence/BAG2_cds_ff_mpt/BAG_framework/bag/io/sim_data.py", line 70, in _get_sweep_params
    mat = np.genfromtxt(fname, dtype=np.unicode_)

  File "/home/mgal/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1700, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))

  File "/home/mgal/anaconda3/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 262, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)

  File "/home/mgal/anaconda3/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 618, in open
    raise IOError("%s not found." % path)

OSError: /home/mgal/Cadence/BAG2_cds_ff_mpt/BAGTMP/simTmp_20181130_2340232vgmmrmy/BagSim_data_20181130_235109pq3dymmi/sweep.info not found.

Best,
Matan

**Comment by pkerichang** [comment]
In the temporary folder (/home/mgal/Cadence/BAG2_cds_ff_mpt/BAGTMP/simTmp_20181130_2340232vgmmrmy):

1. did the ocean script get created?
2. is there a log file in that folder?  What does it say?
3. Can you run the ocean script yourself on commandline manually?  If so, does it work?

**Comment by matangk** [comment]
Hi, 
1. Yes, the ocean script is created.
2. The ocean script runs if loaded from the command line. The strange thing is that once the script is done running, the CIW closes (and virtuoso terminates). Is that intentional?
3. There is definitely a problem with either the way ocean scripts are running in EL7 vs EL6, with permissions, or with my installation (?). Log file of the non-running simulation:
command: ocean -nograph -replay /home/mgal/Cadence/BAG2_cds_ff_mpt/BAGTMP/simTmp_20181130_2340232vgmmrmy/BagSim_data_20181130_23
5109pq3dymmi/run.ocn -log /home/mgal/Cadence/BAG2_cds_ff_mpt/BAGTMP/simTmp_20181130_2340232vgmmrmy/BagSim_data_20181130_235109pq
3dymmi/ocn_output.log
2018/11/30 23:51:09 WARNING This OS does not appear to be a Cadence supported Linux configuration.
2018/11/30 23:51:09 For more info, please run CheckSysConf in <cdsRoot/tools.lnx86/bin/checkSysConf <productId>
*WARNING* Unable to open -nograph X Window Display "hostname:80"
*WARNING* (using "exec /opt/ICADV123/tools.lnx86/dfII/../bin/cdsVncserver :80 -co /usr/share/X11/rgb&").
*WARNING* cdsXvnc output may be found in file $HOME/.vnc-cds/hostname:80.log
Trying another display...
*WARNING* Unable to open -nograph X Window Display "hostname:81"
*WARNING* (using "exec /opt/ICADV123/tools.lnx86/dfII/../bin/cdsVncserver :81 -co /usr/share/X11/rgb&").
*WARNING* cdsXvnc output may be found in file $HOME/.vnc-cds/hostname:81.log
Trying another display...
*WARNING* Unable to open -nograph X Window Display "hostname:82"
*WARNING* (using "exec /opt/ICADV123/tools.lnx86/dfII/../bin/cdsVncserver :82 -co /usr/share/X11/rgb&").
*WARNING* cdsXvnc output may be found in file $HOME/.vnc-cds/hostname:82.log
Trying another display...
*WARNING* Unable to open -nograph X Window Display "hostname:83"
*WARNING* (using "exec /opt/ICADV123/tools.lnx86/dfII/../bin/cdsVncserver :83 -co /usr/share/X11/rgb&").
*WARNING* cdsXvnc output may be found in file $HOME/.vnc-cds/hostname:83.log
Trying another display...
*WARNING* Unable to open -nograph X Window Display "hostname:84"
*WARNING* (using "exec /opt/ICADV123/tools.lnx86/dfII/../bin/cdsVncserver :84 -co /usr/share/X11/rgb&").
*WARNING* cdsXvnc output may be found in file $HOME/.vnc-cds/hostname:84.log
Trying another display...
*WARNING* Unable to open -nograph X Window Display "hostname:85"
*WARNING* (using "exec /opt/ICADV123/tools.lnx86/dfII/../bin/cdsVncserver :85 -co /usr/share/X11/rgb&").
*WARNING* cdsXvnc output may be found in file $HOME/.vnc-cds/hostname:85.log
Trying another display...
*WARNING* Unable to open -nograph X Window Display "hostname:86"
*WARNING* (using "exec /opt/ICADV123/tools.lnx86/dfII/../bin/cdsVncserver :86 -co /usr/share/X11/rgb&").
*WARNING* cdsXvnc output may be found in file $HOME/.vnc-cds/hostname:86.log
Trying another display...
*WARNING* Unable to open -nograph X Window Display "hostname:87"
*WARNING* (using "exec /opt/ICADV123/tools.lnx86/dfII/../bin/cdsVncserver :87 -co /usr/share/X11/rgb&").
*WARNING* cdsXvnc output may be found in file $HOME/.vnc-cds/hostname:87.log
Trying another display...
*WARNING* Unable to open -nograph X Window Display "hostname:88"
*WARNING* (using "exec /opt/ICADV123/tools.lnx86/dfII/../bin/cdsVncserver :88 -co /usr/share/X11/rgb&").
*WARNING* cdsXvnc output may be found in file $HOME/.vnc-cds/hostname:88.log
Trying another display...
*WARNING* Unable to open -nograph X Window Display "hostname:89"
*WARNING* (using "exec /opt/ICADV123/tools.lnx86/dfII/../bin/cdsVncserver :89 -co /usr/share/X11/rgb&").
*WARNING* cdsXvnc output may be found in file $HOME/.vnc-cds/hostname:89.log
*WARNING* Giving up after trying 10 displays.
*WARNING* Unable to connect to a non-graphical X Window Display server.
*WARNING* Try using the -vncTenbase option or the CDS_XVNC_TENBASE environment variable to specify a different set of 10 display
s.


Any thoughts?
Thanks.
Matan

**Comment by pkerichang** [comment]
1. So you are running ocean in a terminal using -nograph, -replay, and -log options?  Why would it close Virtuoso then?  does this ocean command pop up virtuoso GUI?  How would this separate process know anything about the other Virtuoso GUI process?

2. I have no idea about those X errors, some googling may help, or if you can contact cadence support I'll do so.  However, you say that the ocean script still runs?  Does it generate the output data file?

**Comment by matangk** [comment]
1. No, I'm typing load("<run.ocn path>") in the CIW. Sorry, I wasn't clear.

2. Yes, the ocean script runs and results look fine as far as I understand..

**Comment by pkerichang** [comment]
ok, to debug you have to run ocean from terminal, as that is the way BAG runs simulation.  Use the nograph, replay, and log options.

**Comment by matangk** [comment]
Hmm. Interesting. Ocean indeed doesn't run from command-line, and it's the "-nograph" option that makes it fail. That's about as far as my knowledge goes. It can still be a permissions or a missing package issue (installation), or some difference with how the C7 installation handles ocean scripts (unlikely IMO). Any ideas will be welcome..

**Comment by matangk** [comment]
OK. problem solved. Short answer - xorg-x11-fonts packages were missing:
https://community.cadence.com/cadence_technology_forums/f/custom-ic-design/40782/ocean-script-running-on-centos6-but-not-on-centos7
