### ISSUE TITLE
Tool demand

### ISSUE THREAD

**Issue by littleleehan** [ucb-art/BAG2_cds_ff_mpt#13]
Hi:

I am going to use BAG with N28 PDK. I wander what I should do to setup the BAG with it.
Also, I don't have the tool, ICADV 12.3 but IC 5.1.0. Is this tool able to work with BAG? If so, how should I set up the directory?

**Comment by ayan-biswas** [comment]
I am not sure if IC 5.1.0 will work since I have never tried it myself, but here is how you can set it up and try out yourself.
1. If you are using C-shell, modify line 9 in .cshrc as:
setenv CDS_INST_DIR {path to IC 5.1.0}

2. If you are using bash, modify line 9 in .bashrc as:
export CDS_INST_DIR={path to IC 5.1.0}

**Comment by littleleehan** [comment]
Hi:

I am still working on running BAG. What I have done is cloning the repo to my computer and modifying the directory that mentioned in README.
Next, I follow the instruction, "Running BAG", I start icfb and input "load("start_bag.il")" in CIW window.
Then, I got the message, *Error* load: while loading file - "start_bag.il". I think this message means that I have not set up the environment completely. Do I miss anything?

On the other hand, because I will going to use N28 PDK instead of cds_ff_mpt, I did not download the pdk neither doing step 4 and step 7 of installing instruction.
I just intend to setup the environment before dealing with the pdk problem, and I suppose these two steps are not related to the loading error.

**Comment by pkerichang** [comment]
Officially we won't be supported IC 5.1.0.  The main reason being there's a lot of skill API differences between IC version 5 and version 6 (particularly those related to ADEXL, which I'm not sure even exists in IC5) that we don't have the bandwidth to support.  If you don't need to run simulations from BAG and is willing to hunt down all the changes in the skill API and patch the start_bag.il skill script accordingly, I'm open to accepting pull requests.
