### ISSUE TITLE
Do you always have to run a testbench?

### ISSUE THREAD

**Issue by Wencit** [ucb-art/BAG2_cds_ff_mpt#14]
When I create a new class in the specs_demo/demo.yaml file, I don't want to run a testbench but when I comment out the "testbench:" section I get the following error:

KeyError: 'testbenches'

Is there some dummy construct I can insert to the testbench section so it doesn't keep errorring out?

**Comment by jdhan** [comment]
You can just make it empty while still keeping the testbench section, like this
testbenches:

**Comment by Wencit** [comment]
I tried leaving the testbench section empty but I get the following error message when I do:

~/BAG2_cds_ff_mpt/BAG_XBase_demo/scripts_demo/bootcamp_demo.py in gen_schematics(prj, specs, dsn_name, sch_params, check_lvs)
    118             print('lvs log is ' + lvs_log)
    119 
--> 120     for name, info in testbenches.items():
    121         tb_lib = info['tb_lib']
    122         tb_cell = info['tb_cell']

AttributeError: 'NoneType' object has no attribute 'items'

**Comment by eladalon** [comment]
The code that is giving you an error is part of the demo, which is specifically expecting particular testbenches (that are available within the repo) to be run.  In general, you don't need to run a testbench to make BAG work - just this specific demo script is expecting it.
