### ISSUE TITLE
no bootcamp_demo.py file in BAG_XBase_demo/demo_templates

### ISSUE THREAD

**Issue by unnir** [ucb-art/BAG2_cds_ff_mpt#2]
Hi, 

there is no bootcamp_demo.py file in BAG_XBase_demo/demo_templates.

-
Vadim

**Comment by pkerichang** [comment]
We moved away from the script-based approach and now we have Jupyter notebooks.  Please check the new README for instructions.

**Comment by unnir** [comment]
@pkerichang  thank you, a wise move :) I also prefer jupyter notebooks.
