### ISSUE TITLE
Asyncio error with Tornado version 5

### ISSUE THREAD

**Issue by lduncantdkc** [ucb-art/BAG2_cds_ff_mpt#5]
The tutorial produces this error when the latest version of the Tornado package is installed:
**RuntimeError: This event loop is already running**

This appears to be caused by Tornado using the asyncio loop beginning with version 5. This breaks the use of asyncio in BAG when run from the Jupyter notebook. See here for more info:
https://github.com/jupyter/notebook/issues/3397

Temporary workaround is to downgrade Tornado which can be accomplished with pip:
`pip install tornado==4.5.3`

It might be helpful to add this to the documentation and README until the issue is resolved

**Comment by pkerichang** [comment]
Hello,

thank you for the information, detailed about the Python distribution is added in the README file.

Eric
