### ISSUE TITLE
Missing files in repository

### ISSUE THREAD

**Issue by mferriss** [ucb-art/BAG2_cds_ff_mpt#9]
Hi,
I cloned the repository (working from outside of BWRC),
 and after downloading, the directory contains multiple broken symbolic links.
Also, several of the files described in the README file are missing.
e.g.  cds_ff_mpt/workspace_setup/{.cshrc, .bashrc}
or cds_ff_mpt/workspace_setup/{.cshrc_bag, .bashrc_bag}

Looks like the dir "workspace_setup" is missing from the repository?

thanks,
Mark Ferriss

To see the broken symbolic links, run:

git clone  https://github.com/ucb-art/BAG2_cds_ff_mpt.git
cd BAG2_cds_ff_mpt
ls -L

this produces:
ls: cannot access bag_config.yaml: No such file or directory                                                                                                                                                      
ls: cannot access cds.lib.core: No such file or directory                                                                                                                                                         
ls: cannot access display.drf: No such file or directory                                                                                                                                                          
ls: cannot access leBindKeys.il: No such file or directory                                                                                                                                                        
ls: cannot access models: No such file or directory                                                                                                                                                               
ls: cannot access pvtech.lib: No such file or directory                                                                                                                                                           
ls: cannot access setup_submodules.py: No such file or directory                                                                                                                                                  
ls: cannot access specs_test: No such file or directory                                                                                                                                                           
ls: cannot access start_bag.il: No such file or directory                                                                                                                                                         
ls: cannot access start_bag.sh: No such file or directory                                                                                                                                                         
ls: cannot access start_tutorial.sh: No such file or directory                                                                                                                                                    
ls: cannot access tutorial_files: No such file or directory                                                                                                                                                       
ls: cannot access virt_server.sh: No such file or directory 
...

**Comment by sbuchbinder** [comment]
Hi Mark

Try running
git submodule init
git submodule update

I think we might need to switch the order of the install procedure in the README.

Sidney

**Comment by pkerichang** [comment]
sbuchbinder is correct.  I've updated the README instructions.

**Comment by mferriss** [comment]
Thanks Sidney! That worked.
